### ISSUE TITLE
Import error 

### ISSUE THREAD

**Issue by MikSm1th** [drivendataorg/drivendata-submission-validator#7]
Working on a Linux Machine (Ubuntu) pip installed the package.
Ran the following command:
`dd-sub-valid path-to/SubmissionFormat.csv  path-to/predictions.csv`
Received the following Error:
`Traceback (most recent call last):
  File "path-on-my-computer-to/anaconda3/bin/dd-sub-valid", line 6, in <module>
    from drivendata_validator import main
ImportError: cannot import name 'main'`

Applicable versions:
pip 19.1.1
python 3.6.5
conda 4.5.11

**Comment by pjbull** [comment]
Closed by  67987d4, thanks for the report!

Try installing again and running.
